# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1953479da7ccc49b255ff474b63ac6c58695e3c9336c660002a5c736b6ce66e44c94d336f7f558f29f0ec6597348a032421643543ec76cab3bb584a085cec6be

test:
  secret_key_base: d4d60a256e66f520a4f5848af5775e4bc3cb3ad99a5eb7a095b2cbb0275a1f20374917e6026108d33a5dbbe4e798bbd31b0118c6f8789b70f40f8d934328de07

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
